apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-ci-cd-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-ci-cd-2
  template:
    metadata:
      labels:
        app: first-ci-cd-2
    spec:
      containers:
        - name: first-ci-cd-2-server
          image: ghcr.io/sathapornp/first-ci-cd-2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service 
  labels:
    app: hello-service
spec:
  selector:
    app: first-ci-cd-2
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP

