apiVersion: apps/v1
kind: Deployment
metadata:
  name: user13-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user13-service
  template:
    metadata:
      labels:
        app: user13-service
    spec:
      containers:
        - name: user13-server
          image: ghcr.io/sathapornp/first-ci-cd-2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user13-service
  labels:
    app: user13-service
spec:
  selector:
    app: user13-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP

